hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
    
github_login:
    pattern: /login/github

logout:
    pattern: /logout

metagist:
    resource: "@MetagistServerBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine
    
JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /admin/jobs