security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        github_hwi_provider:
             id: metagist.user.provider.entity

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous:         ~
            logout:
                path: /logout
                target: /
            oauth:
                resource_owners:
                    github:          "/login/check-github"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    service: metagist.user.provider.entity

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/package, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contribute, roles: ROLE_USER }
        - { path: ^/contribute-list, roles: ROLE_USER }
        - { path: ^/update, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
