parameters:
  category.icons.mapping:
    homepage: 'icon-home'
    
    api: 'icon-sitemap'
    manual: 'icon-book'
    gettingstarted: 'icon-rocket'
    
    committers: 'icon-group'
    maintainers: 'icon-group'
    usage: 'icon-resize-horizontal'
    
    commits:  'icon-dashboard'
    tests.number:  'icon-dashboard'
    tests.status:  'icon-lightbulb'
    repository:  'icon-github'

  category.render.mapping:
    usage:  {class: 'label label-info'}
    maintainers:  {class: 'badge'}
    committers:  {class: 'badge'}
    commits:  {class: 'badge'}
    #homepage'     => array('displayAs' => 'url'),
    #api'          => array('displayAs' => 'url'),
    #manual'       => array('displayAs' => 'file'),
    #repository'   => array('displayAs' => 'file'),
    #tests.status' => array('displayAs' => 'badge'),
