web:
    resource: "@MetagistServerBundle/Controller/WebController.php"
    type:     annotation

contribute:
    resource: "@MetagistServerBundle/Controller/ContributeController.php"
    type:     annotation

admin_brandings:
    resource: "@MetagistServerBundle/Controller/BrandingController.php"
    type:     annotation
    
admin_packages:
    resource: "@MetagistServerBundle/Controller/PackageController.php"
    type:     annotation