web:
    resource: "@MetagistServerBundle/Controller/WebController.php"
    type:     annotation
    prefix:   /

api:
    resource: "@MetagistServerBundle/Controller/ApiController.php"
    type:     annotation

admin_brandings:
    resource: "@MetagistServerBundle/Controller/BrandingController.php"
    type:     annotation
    
admin_packages:
    resource: "@MetagistServerBundle/Controller/PackageController.php"
    type:     annotation