web:
    resource: "@MetagistServerBundle/Controller/WebController.php"
    type:     annotation
    prefix:   /

api:
    resource: "@MetagistServerBundle/Controller/ApiController.php"
    type:     annotation

api:
    resource: "@MetagistServerBundle/Controller/BrandingController.php"
    type:     annotation