parameters:
    metagist.web.controller.class: Metagist\ServerBundle\Controller\WebController
    metagist.api.controller.class: Metagist\ServerBundle\Controller\ApiController
    metagist.categoryschema.class: Metagist\CategorySchema
    
services:
  metagist_controller_serviceprovider:
    class:     Metagist\ServerBundle\Controller\ServiceProvider
    arguments: ["@service_container"]
    
  metagist.categoryschema:
    class:     "%metagist.categoryschema.class%"
    factory_class:  "%metagist.categoryschema.class%"
    factory_method: create
    arguments: [%kernel.root_dir%/../web/bundles/metagistserver/metainfo.json]
    
  metagist.validator:
    class:     Metagist\Validator
    arguments: ["@metagist.categoryschema"]
    
  metagist_twig_iconextension:
    class:     Metagist\ServerBundle\Twig\Extension\IconExtension
    arguments: [%category.icons.mapping%]
    tags:
      - { name: twig.extension }
  
  metagist_twig_metainfosextension:
    class:     Metagist\ServerBundle\Twig\Extension\MetaInfosExtension
    arguments: [%category.render.mapping%]
    tags:
      - { name: twig.extension }

  metagist.web.controller:
    class:     "%metagist.web.controller.class%"
    arguments: ["@metagist_controller_serviceprovider"]
  
  metagist.api.controller:
    class:     "%metagist.api.controller.class%"
    arguments: ["@metagist_controller_serviceprovider"]
  
  metagist.user.repository:
        class:           Metagist\ServerBundle\Entity\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: ["MetagistServerBundle:User"]
            
  metagist.user.provider.entity:
    class: Metagist\ServerBundle\Entity\UserProvider
    arguments: ["@metagist.user.repository"]
    
  metagist.opauth.listener:
    class: Metagist\ServerBundle\EventListener\OpauthListener
    arguments: ["@doctrine.orm.entity_manager"]
    
  metagist.api:
    class: Metagist\Api\Factory
    calls:
      - [setConfig, [%metagist.api.config%]]
  
  metagist.api.request_validator:
    class: Metagist\Api\RequestValidator
    arguments: ["@event_dispatcher"]