<?php

namespace Metagist\ServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandingRepository extends EntityRepository
{
}
